archives:
- id: archive
  name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
  - make tfgen
builds:
- binary: pulumi-resource-acme
  dir: provider
  goarch:
  - amd64
  - arm64
  goos:
  - darwin
  - windows
  - linux
  ignore: []
  ldflags:
  - -X github.com/pulumi/pulumi-xyz/provider/pkg/version.Version={{.Tag}}
  main: ./cmd/pulumi-resource-acme/
  #sort: asc
  #use: git
release:
  disable: false
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
